"""add daily site reports quality safety domain

Revision ID: 04d3e460a8a7
Revises: eaf5b6c0d061
Create Date: 2026-08-25 05:10:55.139760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d3e460a8a7'
down_revision: Union[str, None] = 'f66768a419c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_site_reports',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('weather', sa.String(length=64), nullable=True),
    sa.Column('workforce_summary', sa.String(length=2000), nullable=True),
    sa.Column('activities_performed', sa.String(length=4000), nullable=False),
    sa.Column('equipment_used', sa.String(length=2000), nullable=True),
    sa.Column('materials_used', sa.String(length=2000), nullable=True),
    sa.Column('incidents', sa.String(length=2000), nullable=True),
    sa.Column('observations', sa.String(length=2000), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED')", name='ck_daily_site_reports_status_valid'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_incidents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('corrective_action', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='ck_safety_incidents_severity_valid'),
    sa.CheckConstraint("severity NOT IN ('HIGH','CRITICAL') OR responsible_user_id IS NOT NULL", name='ck_safety_incidents_high_severity_requires_responsible'),
    sa.CheckConstraint("status IN ('OPEN','CLOSED')", name='ck_safety_incidents_status_valid'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_observations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('corrective_action', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='ck_safety_observations_severity_valid'),
    sa.CheckConstraint("severity NOT IN ('HIGH','CRITICAL') OR responsible_user_id IS NOT NULL", name='ck_safety_observations_high_severity_requires_responsible'),
    sa.CheckConstraint("status IN ('OPEN','CLOSED')", name='ck_safety_observations_status_valid'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_site_report_photos',
    sa.Column('daily_site_report_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_site_report_id'], ['daily_site_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_inspections',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('wbs_node_id', sa.UUID(), nullable=True),
    sa.Column('inspection_type', sa.String(length=128), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result IN ('PENDING','PASS','FAIL')", name='ck_quality_inspections_result_valid'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wbs_node_id'], ['wbs_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_conformances',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('quality_inspection_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CLOSED')", name='ck_non_conformances_status_valid'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quality_inspection_id'], ['quality_inspections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corrective_actions',
    sa.Column('non_conformance_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','COMPLETED')", name='ck_corrective_actions_status_valid'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['non_conformance_id'], ['non_conformances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corrective_actions')
    op.drop_table('non_conformances')
    op.drop_table('quality_inspections')
    op.drop_table('daily_site_report_photos')
    op.drop_table('safety_observations')
    op.drop_table('safety_incidents')
    op.drop_table('daily_site_reports')
    # ### end Alembic commands ###
