"""add project control domain wbs planning budget change orders progress

Revision ID: 131a6debf189
Revises: c622defc2308
Create Date: 2026-08-24 12:35:51.357556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131a6debf189'
down_revision: Union[str, None] = 'c622defc2308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wbs_nodes',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('manager', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['wbs_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_wbs_nodes_project_code')
    )
    op.create_table('change_orders',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('wbs_node_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('scope_change', sa.String(length=2000), nullable=True),
    sa.Column('budget_change_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('schedule_change_days', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wbs_node_id'], ['wbs_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('wbs_node_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('achieved_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wbs_node_id'], ['wbs_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_records',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('wbs_node_id', sa.UUID(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('planned_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('actual_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_ref', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wbs_node_id'], ['wbs_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('wbs_node_id', sa.UUID(), nullable=True),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wbs_node_id'], ['wbs_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('previous_budget_id', sa.UUID(), nullable=True),
    sa.Column('change_order_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['previous_budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_lines',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('wbs_node_id', sa.UUID(), nullable=True),
    sa.Column('economic_category_id', sa.UUID(), nullable=True),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=True),
    sa.Column('authorized_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['economic_category_id'], ['economic_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wbs_node_id'], ['wbs_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('code', sa.String(length=32), nullable=True))
    op.add_column('projects', sa.Column('customer_ref', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('manager', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.add_column('projects', sa.Column('cost_center_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('planned_start', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('planned_end', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('actual_end', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('description', sa.String(length=2000), nullable=True))
    op.create_foreign_key('fk_projects_currency_code', 'projects', 'currencies', ['currency_code'], ['code'])
    op.create_foreign_key(
        'fk_projects_cost_center_id', 'projects', 'cost_centers', ['cost_center_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_cost_center_id', 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_currency_code', 'projects', type_='foreignkey')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'actual_end')
    op.drop_column('projects', 'planned_end')
    op.drop_column('projects', 'planned_start')
    op.drop_column('projects', 'cost_center_id')
    op.drop_column('projects', 'currency_code')
    op.drop_column('projects', 'manager')
    op.drop_column('projects', 'customer_ref')
    op.drop_column('projects', 'code')
    op.drop_table('budget_lines')
    op.drop_table('budgets')
    op.drop_table('tasks')
    op.drop_table('progress_records')
    op.drop_table('milestones')
    op.drop_table('change_orders')
    op.drop_table('wbs_nodes')
    # ### end Alembic commands ###
