"""restore_supplier_and_asset_check_constraints

Revision ID: 19f77fdb5abe
Revises: adfb3df167f0
Create Date: 2026-09-11 14:20:21.670177

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '19f77fdb5abe'
down_revision: Union[str, None] = 'adfb3df167f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_fixed_assets_accumulated_depreciation_non_negative', 'fixed_assets', 'COALESCE(accumulated_depreciation, 0) >= 0')
    op.create_check_constraint('ck_fixed_assets_disposal_date', 'fixed_assets', "(status NOT IN ('DISPOSED','RETIRED')) OR disposal_date IS NOT NULL")
    op.create_check_constraint('ck_fixed_assets_disposal_proceeds_non_negative', 'fixed_assets', 'COALESCE(disposal_proceeds, 0) >= 0')
    op.create_check_constraint('ck_suppliers_party_role', 'suppliers', "party_role IN ('SUPPLIER','CONTRACTOR','BOTH')")
    op.create_check_constraint('ck_suppliers_status', 'suppliers', "status IN ('ACTIVE','INACTIVE','BLOCKED','ARCHIVED')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_suppliers_status', 'suppliers', type_='check')
    op.drop_constraint('ck_suppliers_party_role', 'suppliers', type_='check')
    op.drop_constraint('ck_fixed_assets_disposal_proceeds_non_negative', 'fixed_assets', type_='check')
    op.drop_constraint('ck_fixed_assets_disposal_date', 'fixed_assets', type_='check')
    op.drop_constraint('ck_fixed_assets_accumulated_depreciation_non_negative', 'fixed_assets', type_='check')
    # ### end Alembic commands ###
