"""add treasury ap ar financial core

Revision ID: 58ce35982711
Revises: c622defc2308
Create Date: 2026-08-24 12:37:59.398814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ce35982711'
down_revision: Union[str, None] = 'c622defc2308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'accounting_documents_document_number_key',
        'accounting_documents',
        type_='unique',
    )
    op.create_unique_constraint(
        'uq_accounting_documents_company_document_number',
        'accounting_documents',
        ['company_id', 'document_number'],
    )
    op.create_table('customer_invoices',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('revenue_account_id', sa.UUID(), nullable=False),
    sa.Column('receivable_account_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_collected', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('accounting_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounting_document_id'], ['accounting_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receivable_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revenue_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.CheckConstraint('amount > 0', name='ck_customer_invoices_amount_positive'),
    sa.CheckConstraint('amount_collected >= 0 AND amount_collected <= amount', name='ck_customer_invoices_collected_within_total'),
    sa.CheckConstraint("(scope IN ('CENTRAL','GENERAL') AND project_id IS NULL) OR (scope = 'PROJECT' AND project_id IS NOT NULL)", name='ck_customer_invoices_operation_scope'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_invoices',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_tax_id', sa.String(length=64), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.Column('expense_account_id', sa.UUID(), nullable=False),
    sa.Column('payable_account_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('accrual_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accrual_document_id'], ['accounting_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payable_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.CheckConstraint('amount > 0', name='ck_supplier_invoices_amount_positive'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_supplier_invoices_tax_non_negative'),
    sa.CheckConstraint('amount_paid >= 0 AND amount_paid <= amount + tax_amount', name='ck_supplier_invoices_paid_within_total'),
    sa.CheckConstraint("(scope IN ('CENTRAL','GENERAL') AND project_id IS NULL) OR (scope = 'PROJECT' AND project_id IS NOT NULL)", name='ck_supplier_invoices_operation_scope'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treasury_accounts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('account_reference', sa.String(length=64), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('gl_account_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['gl_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.CheckConstraint("kind IN ('BANK','CASH','OTHER')", name='ck_treasury_accounts_kind'),
    sa.CheckConstraint("status IN ('ACTIVE','CLOSED')", name='ck_treasury_accounts_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_statements',
    sa.Column('treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['treasury_account_id'], ['treasury_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_closings',
    sa.Column('treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('counted_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('difference_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('accounting_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounting_document_id'], ['accounting_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treasury_account_id'], ['treasury_accounts.id'], ondelete='RESTRICT'),
    sa.CheckConstraint('opening_amount >= 0 AND expected_amount >= 0 AND counted_amount >= 0', name='ck_cash_closings_amounts_non_negative'),
    sa.CheckConstraint("status IN ('DRAFT','APPROVED')", name='ck_cash_closings_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_receipts',
    sa.Column('customer_invoice_id', sa.UUID(), nullable=False),
    sa.Column('treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('accounting_document_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounting_document_id'], ['accounting_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_invoice_id'], ['customer_invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treasury_account_id'], ['treasury_accounts.id'], ondelete='RESTRICT'),
    sa.CheckConstraint('amount > 0', name='ck_customer_receipts_amount_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_restrictions',
    sa.Column('treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('restricted_for_project_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restricted_for_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['treasury_account_id'], ['treasury_accounts.id'], ondelete='CASCADE'),
    sa.CheckConstraint('amount > 0', name='ck_fund_restrictions_amount_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_expenses',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('expense_account_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('accounting_document_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounting_document_id'], ['accounting_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treasury_account_id'], ['treasury_accounts.id'], ondelete='RESTRICT'),
    sa.CheckConstraint('amount > 0', name='ck_general_expenses_amount_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remittances',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('counter_account_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('remittance_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('accounting_document_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounting_document_id'], ['accounting_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['counter_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['treasury_account_id'], ['treasury_accounts.id'], ondelete='RESTRICT'),
    sa.CheckConstraint('original_amount > 0 AND fx_rate > 0 AND base_amount > 0', name='ck_remittances_amounts_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_payments',
    sa.Column('supplier_invoice_id', sa.UUID(), nullable=False),
    sa.Column('treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('accounting_document_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounting_document_id'], ['accounting_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_invoice_id'], ['supplier_invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treasury_account_id'], ['treasury_accounts.id'], ondelete='RESTRICT'),
    sa.CheckConstraint('amount > 0', name='ck_supplier_payments_amount_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treasury_transfers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('destination_treasury_account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('accounting_document_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_treasury_account_id <> destination_treasury_account_id', name='ck_treasury_transfers_distinct_accounts'),
    sa.CheckConstraint('amount > 0', name='ck_treasury_transfers_amount_positive'),
    sa.ForeignKeyConstraint(['accounting_document_id'], ['accounting_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['destination_treasury_account_id'], ['treasury_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_treasury_account_id'], ['treasury_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_statement_lines',
    sa.Column('bank_statement_id', sa.UUID(), nullable=False),
    sa.Column('line_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_statement_id'], ['bank_statements.id'], ondelete='CASCADE'),
    sa.CheckConstraint('amount <> 0', name='ck_bank_statement_lines_amount_non_zero'),
    sa.CheckConstraint("status IN ('UNMATCHED','MATCHED','PARTIAL','EXCLUDED')", name='ck_bank_statement_lines_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_matches',
    sa.Column('bank_statement_line_id', sa.UUID(), nullable=False),
    sa.Column('accounting_document_id', sa.UUID(), nullable=False),
    sa.Column('matched_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('matched_by_user_id', sa.UUID(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounting_document_id'], ['accounting_documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bank_statement_line_id'], ['bank_statement_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.CheckConstraint('matched_amount > 0', name='ck_reconciliation_matches_amount_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_matches')
    op.drop_table('bank_statement_lines')
    op.drop_table('treasury_transfers')
    op.drop_table('supplier_payments')
    op.drop_table('remittances')
    op.drop_table('general_expenses')
    op.drop_table('fund_restrictions')
    op.drop_table('customer_receipts')
    op.drop_table('cash_closings')
    op.drop_table('bank_statements')
    op.drop_table('treasury_accounts')
    op.drop_table('supplier_invoices')
    op.drop_table('customer_invoices')
    op.drop_constraint(
        'uq_accounting_documents_company_document_number',
        'accounting_documents',
        type_='unique',
    )
    op.create_unique_constraint(
        'accounting_documents_document_number_key',
        'accounting_documents',
        ['document_number'],
    )
    # ### end Alembic commands ###
