"""add enterprise resources: assets equipment maintenance workforce

Revision ID: 7423072b11d4
Revises: a91c7d4e2f36
Create Date: 2026-08-24 19:37:26.377873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7423072b11d4'
down_revision: Union[str, None] = 'a91c7d4e2f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=128), nullable=True),
    sa.Column('standard_hourly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('standard_hourly_rate > 0', name='ck_workers_standard_rate_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_assets',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.Column('depreciation_expense_account_id', sa.UUID(), nullable=False),
    sa.Column('accumulated_depreciation_account_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope IN ('CENTRAL','GENERAL') AND project_id IS NULL) OR (scope = 'PROJECT' AND project_id IS NOT NULL)", name='ck_fixed_assets_operation_scope'),
    sa.CheckConstraint("status IN ('ACTIVE','UNDER_MAINTENANCE','DISPOSED','RETIRED')", name='ck_fixed_assets_status_valid'),
    sa.CheckConstraint('cost > 0', name='ck_fixed_assets_cost_positive'),
    sa.CheckConstraint('salvage_value < cost', name='ck_fixed_assets_salvage_below_cost'),
    sa.CheckConstraint('salvage_value >= 0', name='ck_fixed_assets_salvage_non_negative'),
    sa.CheckConstraint('useful_life_months > 0', name='ck_fixed_assets_useful_life_positive'),
    sa.ForeignKeyConstraint(['accumulated_depreciation_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['depreciation_expense_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_entries',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope IN ('CENTRAL','GENERAL') AND project_id IS NULL) OR (scope = 'PROJECT' AND project_id IS NOT NULL)", name='ck_time_entries_operation_scope'),
    sa.CheckConstraint("status IN ('SUBMITTED','APPROVED','REJECTED')", name='ck_time_entries_status_valid'),
    sa.CheckConstraint('approved_hours IS NULL OR approved_hours >= 0', name='ck_time_entries_approved_hours_non_negative'),
    sa.CheckConstraint('hourly_rate > 0', name='ck_time_entries_hourly_rate_positive'),
    sa.CheckConstraint('hours_worked > 0', name='ck_time_entries_hours_worked_positive'),
    sa.CheckConstraint('labor_cost IS NULL OR labor_cost >= 0', name='ck_time_entries_labor_cost_non_negative'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depreciation_entries',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('accounting_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_depreciation_entries_amount_positive'),
    sa.CheckConstraint('period_end >= period_start', name='ck_depreciation_entries_period_valid'),
    sa.ForeignKeyConstraint(['accounting_document_id'], ['accounting_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['fixed_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_start', name='uq_depreciation_entries_asset_period')
    )
    op.create_table('equipment',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('equipment_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('plate_number', sa.String(length=32), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('hour_meter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('odometer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('AVAILABLE','IN_USE','UNDER_MAINTENANCE','OUT_OF_SERVICE')", name='ck_equipment_status_valid'),
    sa.CheckConstraint('hour_meter >= 0', name='ck_equipment_hour_meter_non_negative'),
    sa.CheckConstraint('odometer >= 0', name='ck_equipment_odometer_non_negative'),
    sa.ForeignKeyConstraint(['asset_id'], ['fixed_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_logs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_description', sa.String(length=255), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'GENERAL' AND project_id IS NULL) OR (scope = 'PROJECT' AND project_id IS NOT NULL)", name='ck_fuel_logs_operation_scope'),
    sa.CheckConstraint('quantity > 0', name='ck_fuel_logs_quantity_positive'),
    sa.CheckConstraint('total_cost > 0', name='ck_fuel_logs_total_cost_positive'),
    sa.CheckConstraint('unit_cost > 0', name='ck_fuel_logs_unit_cost_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_plans',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('trigger_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('trigger_value > 0', name='ck_maintenance_plans_trigger_value_positive'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_orders',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('supplier_ref', sa.String(length=255), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('downtime_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("order_type IN ('PREVENTIVE','CORRECTIVE')", name='ck_maintenance_orders_type_valid'),
    sa.CheckConstraint("status IN ('OPEN','IN_PROGRESS','CLOSED','CANCELLED')", name='ck_maintenance_orders_status_valid'),
    sa.CheckConstraint('downtime_hours >= 0', name='ck_maintenance_orders_downtime_hours_non_negative'),
    sa.CheckConstraint('labor_cost >= 0', name='ck_maintenance_orders_labor_cost_non_negative'),
    sa.CheckConstraint('parts_cost >= 0', name='ck_maintenance_orders_parts_cost_non_negative'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['maintenance_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_orders')
    op.drop_table('maintenance_plans')
    op.drop_table('fuel_logs')
    op.drop_table('equipment')
    op.drop_table('depreciation_entries')
    op.drop_table('time_entries')
    op.drop_table('fixed_assets')
    op.drop_table('workers')
    # ### end Alembic commands ###
