"""add cash flow activity classification to accounts

Revision ID: 8496f11b1227
Revises: c15db6e5d9ca
Create Date: 2026-08-25 21:24:36.309141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8496f11b1227'
down_revision: Union[str, None] = 'c15db6e5d9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('cash_flow_activity', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'cash_flow_activity')
    # ### end Alembic commands ###
