"""sync_model_changes_post_pr134

Revision ID: adfb3df167f0
Revises: f2c3d4e5f6a7
Create Date: 2026-09-11 13:57:51.715373

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'adfb3df167f0'
down_revision: Union[str, None] = 'f2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_companies_logo_evidence'), 'companies', type_='foreignkey')
    op.drop_constraint(op.f('fk_companies_signature_evidence'), 'companies', type_='foreignkey')
    op.drop_constraint(op.f('ck_fixed_assets_accumulated_depreciation_non_negative'), 'fixed_assets', type_='check')
    op.drop_constraint(op.f('ck_fixed_assets_disposal_date'), 'fixed_assets', type_='check')
    op.drop_constraint(op.f('ck_fixed_assets_disposal_proceeds_non_negative'), 'fixed_assets', type_='check')
    op.drop_constraint(op.f('fk_physical_counts_inventory_account'), 'physical_counts', type_='foreignkey')
    op.drop_constraint(op.f('fk_physical_counts_adjustment_gain_account'), 'physical_counts', type_='foreignkey')
    op.drop_constraint(op.f('fk_physical_counts_adjustment_loss_account'), 'physical_counts', type_='foreignkey')
    op.drop_column('physical_counts', 'adjustment_gain_account_id')
    op.drop_column('physical_counts', 'inventory_account_id')
    op.drop_column('physical_counts', 'adjustment_loss_account_id')
    op.drop_index(op.f('ix_purchase_orders_supplier_contract_id'), table_name='purchase_orders')
    op.drop_constraint(op.f('ck_purchase_requisitions_priority_valid'), 'purchase_requisitions', type_='check')
    op.drop_index(op.f('ix_supplier_invoice_plan_invoice'), table_name='supplier_invoice_payment_plan_items')
    op.drop_constraint(op.f('uq_supplier_invoice_plan_sequence'), 'supplier_invoice_payment_plan_items', type_='unique')
    op.drop_index(op.f('ix_supplier_invoices_purchase_order_id'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_supplier_contract_id'), table_name='supplier_invoices')
    op.drop_constraint(op.f('ck_suppliers_party_role'), 'suppliers', type_='check')
    op.drop_constraint(op.f('ck_suppliers_status'), 'suppliers', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_suppliers_status'), 'suppliers', "status::text = ANY (ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BLOCKED'::character varying, 'ARCHIVED'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_suppliers_party_role'), 'suppliers', "party_role::text = ANY (ARRAY['SUPPLIER'::character varying, 'CONTRACTOR'::character varying, 'BOTH'::character varying]::text[])")
    op.create_index(op.f('ix_supplier_invoices_supplier_contract_id'), 'supplier_invoices', ['supplier_contract_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_purchase_order_id'), 'supplier_invoices', ['purchase_order_id'], unique=False)
    op.create_unique_constraint(op.f('uq_supplier_invoice_plan_sequence'), 'supplier_invoice_payment_plan_items', ['supplier_invoice_id', 'sequence'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_supplier_invoice_plan_invoice'), 'supplier_invoice_payment_plan_items', ['supplier_invoice_id'], unique=False)
    op.create_check_constraint(op.f('ck_purchase_requisitions_priority_valid'), 'purchase_requisitions', "priority::text = ANY (ARRAY['LOW'::character varying, 'NORMAL'::character varying, 'HIGH'::character varying, 'URGENT'::character varying]::text[])")
    op.create_index(op.f('ix_purchase_orders_supplier_contract_id'), 'purchase_orders', ['supplier_contract_id'], unique=False)
    op.add_column('physical_counts', sa.Column('adjustment_loss_account_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('physical_counts', sa.Column('inventory_account_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('physical_counts', sa.Column('adjustment_gain_account_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_physical_counts_adjustment_loss_account'), 'physical_counts', 'accounts', ['adjustment_loss_account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_physical_counts_adjustment_gain_account'), 'physical_counts', 'accounts', ['adjustment_gain_account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_physical_counts_inventory_account'), 'physical_counts', 'accounts', ['inventory_account_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint(op.f('ck_fixed_assets_disposal_proceeds_non_negative'), 'fixed_assets', 'COALESCE(disposal_proceeds, 0::numeric) >= 0::numeric')
    op.create_check_constraint(op.f('ck_fixed_assets_disposal_date'), 'fixed_assets', "(status::text <> ALL (ARRAY['DISPOSED'::character varying, 'RETIRED'::character varying]::text[])) OR disposal_date IS NOT NULL")
    op.create_check_constraint(op.f('ck_fixed_assets_accumulated_depreciation_non_negative'), 'fixed_assets', 'COALESCE(accumulated_depreciation, 0::numeric) >= 0::numeric')
    op.create_foreign_key(op.f('fk_companies_signature_evidence'), 'companies', 'evidence', ['signature_evidence_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_companies_logo_evidence'), 'companies', 'evidence', ['logo_evidence_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
