"""add login lockout fields to users

Revision ID: c15db6e5d9ca
Revises: 24e79c9cb218
Create Date: 2026-08-25 17:47:56.950130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15db6e5d9ca'
down_revision: Union[str, None] = '24e79c9cb218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default requerido: NOT NULL sobre una tabla con filas existentes
    # (el `default=0` de SQLAlchemy solo aplica a INSERTs nuevos, nunca a un
    # ALTER TABLE). Se quita el default a nivel de servidor después de
    # backfillear, para que quede igual que si la tabla se hubiera creado
    # desde cero con este esquema.
    op.add_column(
        'users',
        sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('users', 'failed_login_attempts', server_default=None)
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
