"""add documents evidence and progress record evidence fk

Revision ID: eaf5b6c0d061
Revises: f1075e290473
Create Date: 2026-08-25 04:21:33.341604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf5b6c0d061'
down_revision: Union[str, None] = 'f1075e290473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('blob_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name='ck_evidence_size_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blob_key')
    )
    op.create_table('documents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope IN ('CENTRAL','GENERAL') AND project_id IS NULL) OR (scope = 'PROJECT' AND project_id IS NOT NULL)", name='ck_documents_operation_scope'),
    sa.CheckConstraint("category IN ('CONTRACT','DRAWING','PERMIT','REPORT','SAFETY','QUALITY','PHOTO','OTHER')", name='ck_documents_category_valid'),
    sa.CheckConstraint("status IN ('ACTIVE','ARCHIVED')", name='ck_documents_status_valid'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','SUPERSEDED')", name='ck_document_versions_status_valid'),
    sa.CheckConstraint('version_number > 0', name='ck_document_versions_number_positive'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_versions_document_number')
    )
    op.create_index('uq_document_versions_one_active_per_document', 'document_versions', ['document_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.add_column('progress_records', sa.Column('evidence_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'progress_records', 'evidence', ['evidence_id'], ['id'], ondelete='SET NULL')
    op.drop_column('progress_records', 'evidence_ref')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_records', sa.Column('evidence_ref', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'progress_records', type_='foreignkey')
    op.drop_column('progress_records', 'evidence_id')
    op.drop_index('uq_document_versions_one_active_per_document', table_name='document_versions', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('document_versions')
    op.drop_table('documents')
    op.drop_table('evidence')
    # ### end Alembic commands ###
